### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rlatmfrl24** [rlatmfrl24/chamomile-next#1]
- [x] 프로젝트 디테일에 프로젝트 종류 라벨 붙이기
- [x] 프로젝트 가능한 Git Repo 연결
- [x] 프로젝트 디테일용 레이아웃 리서치
https://www.pinterest.co.kr/pin/744431013425453544/
- [x] About 페이지 관련 Height 이슈 조사 및 최소 높이 적용 고려
- [ ] 마크다운 파싱 관련하여 Blog에 적용 고려
- [x] 페이지 전체에 폰트 변경 적용 고려
- [x] 프로젝트 디테일에서 사진 클릭시 확장 화면 추가
